コメント機能追加
alingen/twitter_clone2 pull request #4
Opened 2023-01-24 12:30 UTC by alingen

コメント機能を追加しました

2023-01-24 13:27 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +    @tweet = Tweet.find_by(id: params[:id])
find_byだとnilが返り、間違ったparams[:id]でもエラーが起きないため
findのほうがよいでしょう。

```suggestion
    @tweet = Tweet.find(params[:id])
```

2023-01-24 13:27 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +    @comments = Comment.where(tweet_id: @tweet.id)
アソシエーションを使いましょう。

```suggestion
    @comments = @tweet.comments
```

2023-01-24 13:29 UTC, ihatov08 commented on config/routes.rb
> +  get 'comments/:id/new' => 'comments#new', as: 'comment_new'
resourcesを使ってください。

2023-01-24 13:29 UTC, ihatov08 commented on config/routes.rb
> +  post 'comments/:id/create' => 'comments#create', as: 'comment_create'
こちらもresourcesを使って定義してください。

2023-01-24 13:30 UTC, ihatov08 commented on config/routes.rb
> +  resources :tweets, :comments
こちらでresourcesで定義しているのであれば、以下のコードは不要です。

```
get 'comments/:id/new' => 'comments#new', as: 'comment_new'
post 'comments/:id/create' => 'comments#create', as: 'comment_create'
```

2023-01-24 13:31 UTC, ihatov08 commented on config/routes.rb
> +  resources :tweets, :comments
resourcesはonlyオプションを定義することを考慮して別々に定義したほうがよいです。

```suggestion
  resources :tweets
  resources :comments
```

2023-01-25 06:23 UTC, ihatov08 commented on app/views/tweets/show.html.slim
> +        = link_to 'コメント', new_tweet_comment_path(params[:id])
params[:id]が何を指すのかわかりづらいので、new_tweet_comment_path(@tweet.id)のほうがよいと思います。

2023-01-25 06:38 UTC, ihatov08 commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: params[:tweet_id]) do |f|
tweet_comments_pathにid path paramsは存在しないので、使い方が間違っていると思います。

![Routes](https://user-images.githubusercontent.com/14024165/214496357-f4f4b517-81c4-44ed-9aee-eb08e3278249.png)

comments controller newアクションで@tweetを設定して、
tweet_comments_path(@tweet)とするべきです。

この状態だと存在しないツイートidに対してコメント画面が表示できてしまいます。

2023-01-25 06:41 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +    @comment = current_user.comments.build(tweet_id: params[:id], text: params[:text])
comments controllerでparams[:id]はcommentのidであるべきでtweetのidで使うべきではありません。
またtweetが存在するのかcomments.buildの前に確認して、存在しない場合は404エラーを起こすべきです。
```ruby
    before_action :set_tweet, only: [:new, :create]
    
    def create
      @comment = current_user.comments.build(tweet_id: @tweet.id, text: params[:text])
    end
    
    private
    
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
```

2023-01-25 06:42 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +      redirect_to tweet_path(params[:id])
```suggestion
      redirect_to tweet_path(@tweet)
```

2023-01-25 06:42 UTC, ihatov08 commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: params[:tweet_id]) do |f|
form_withにはmodelオプションも渡しましょう。

2023-01-31 07:06 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +    if @tweet = Tweet.find(params[:tweet_id])
この処理はnew,create共通なのでbefore_actionでまとめましょう。

```ruby
before_action :set_tweet, only: %i[new, create]

private

def set_tweet
  @tweet = Tweet.find(params[:tweet_id])
end

2023-01-31 07:07 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +    if @tweet = Tweet.find(params[:tweet_id])
Tweet.findで存在しなければ例外が発生するので、ifで条件分岐は不要です。

2023-01-31 07:08 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +      @comment = current_user.comments.build(tweet_id: params[:tweet_id], text: params[:text])
バグに気づきづらいので、build時になるべくparamsを参照しないほうがよいでしょう。

```suggestion
      @comment = current_user.comments.build(tweet_id: @tweet.id, text: params[:text])
```

2023-01-31 07:09 UTC, ihatov08 commented on config/environments/production.rb
> +  config.assets.compile = true
productionでasset compileは特段の理由が無い限りfalseです。
これだとcompileが走ってしまい、遅くなります。

2023-01-31 07:11 UTC, ihatov08 requested changes

2023-01-31 07:11 UTC, ihatov08 commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: @tweet), model: @comment do |f|
tweet_comments_pathにid paramsで@tweetを渡している理由を教えてください。
通常はtweet_comments_path(@tweet)もしくはtweet_comments_path(tweet_id: @tweet.id)となるはずです。

2023-01-31 07:11 UTC, ihatov08 commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: @tweet), model: @comment do |f|
@commentはnilになっているようなので指定する意味がなさそうです。
newアクションで@commentにcommentクラスのインスタンスをセットしてください。

2023-01-31 07:12 UTC, ihatov08 commented on app/controllers/application_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :render_404
controllerで404をrescue_fromする必要は特段の理由が無い限り不要です。

2023-01-31 07:13 UTC, ihatov08 commented on app/controllers/application_controller.rb
> +      render file: Rails.root.join('public/404.html'), status: 404, layout: false, content_type: 'text/html'
public/404.htmlはproduction環境だと自動で表示されるようになっているので、こちらの処理は不要です。
開発環境でもpublic/404.htmlが表示されエラーがわかりづらくなります。

2023-03-03 14:39 UTC, ihatov08 commented on app/controllers/comments_controller.rb
> +    @comments = Comment.new
@commentsで複数形なのは違和感があります
またユーザーにひもづくコメントなのでcurrent_user.comments.buildが適切でしょう。

2023-03-03 14:40 UTC, ihatov08 commented on app/controllers/tweets_controller.rb
> +    @comments = @tweet.comments
@tweet.commentsで取得できるようにすれば@commentsは不要です。

2023-03-03 14:41 UTC, ihatov08 commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: @tweet), model: @comment do |f|
> tweet_comments_pathにid paramsで@tweetを渡している理由を教えてください。 通常はtweet_comments_path(@tweet)もしくはtweet_comments_path(tweet_id: @tweet.id)となるはずです。

こちらご回答お願いします

2023-03-03 22:27 UTC, alingen commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: @tweet), model: @comment do |f|
urlの情報からtweet_idを読み取るためにそのようにしていました。paramsで渡すとなにか問題がありますでしょうか？

2023-03-07 07:26 UTC, ihatov08 commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: @tweet), model: @comment do |f|
`tweet_comments_path`だとid parameterはcommentのidを連想させます。
tweetのidを渡したいならtweet_id parameterとして渡すべきだと思います。

2023-03-07 07:26 UTC, ihatov08 commented on app/views/comments/new.html.slim
> +    = form_with url: tweet_comments_path(id: @tweet), model: @comment do |f|
`tweets/:tweet_id/comments`
↑のようなパスでtweetのcommentを作成したいですね。

2023-03-08 01:24 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-03-08 07:52 UTC, merged